### ISSUE TITLE
Findbugs broken on JDK9

### ISSUE THREAD

**Issue by offa** [offa/NBCndUnit#36]
Findbugs broken on JDK9:

```
[…]
     [java] Warning: Unknown version of Java
     [java] edu.umd.cs.findbugs.JavaVersionException: Could not parse Java version string: 9
     [java] 	at edu.umd.cs.findbugs.JavaVersion.<init>(JavaVersion.java:68)
     [java] 	at edu.umd.cs.findbugs.JavaVersion.<clinit>(JavaVersion.java:44)
     [java] 	at edu.umd.cs.findbugs.DetectorFactory.isEnabledForCurrentJRE(DetectorFactory.java:248)
[…]
```

**Comment by offa** [comment]
Switching to Spotbugs (#35) is an option.

**Comment by offa** [comment]
**Ref.** #34

**Comment by offa** [comment]
I think Findbugs wont get an update to fix this. So removing it and use *Spotbugs* instead sounds consequent.
